FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD swipeinoutservice.jar /opt/swipeinoutservice/
EXPOSE 8080
WORKDIR /opt/swipeinoutservice/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "swipeinoutservice.jar"]
